# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins]
# zsh-defer is required for defer template
[plugins.zsh-defer]
github = "romkatv/zsh-defer"

# For example:
#
# [plugins.base16]
# [plugins]
[plugins.zeno]
github = "yuki-yano/zeno.zsh"

[plugins.zeno.hooks]
pre = '''
export ZENO_HOME=~/.config/zeno
export ZENO_GIT_CAT="bat --color=always"
'''
post = '''
bindkey ' ' zeno-auto-snippet
bindkey '^m' zeno-auto-snippet-and-accept-line
bindkey '^i' zeno-completion
bindkey '^xx' zeno-insert-snippet
bindkey '^x ' zeno-insert-space
bindkey '^x^m' accept-line
bindkey '^x^z' zeno-toggle-auto-snippet
bindkey '^xp' zeno-preprompt
bindkey '^xs' zeno-preprompt-snippet
bindkey '^r' zeno-smart-history-selection
bindkey '^g' zeno-ghq-cd
'''
[plugins.fast-syntax-highlighting]
github = "zdharma-continuum/fast-syntax-highlighting"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-autosuggestions.hooks]
post = '''
ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=#999,bg=transparent,bold,underline'
'''
